import type React from "react";
import type { ColorPalette } from "../theme/palettes.js";
import { fontFamilies, radius, shadow, spacing, typography } from "../theme/tokens.js";

export const createDocumentSurfaceStyles = (
  colors: ColorPalette,
  isNarrow: boolean,
): Record<string, React.CSSProperties> => ({
  root: {
    display: "grid",
    gridTemplateColumns: isNarrow ? "minmax(0, 1fr)" : "minmax(220px, 280px) minmax(0, 1fr)",
    gridTemplateRows: isNarrow ? "auto minmax(0, 1fr)" : undefined,
    height: "100%",
    minHeight: 0,
    background: colors.bg,
  },
  rail: {
    minWidth: 0,
    borderRight: `1px solid ${colors.border}`,
    borderBottom: isNarrow ? `1px solid ${colors.border}` : undefined,
    background: colors.surface,
    padding: isNarrow ? spacing.md : spacing.lg,
    overflow: "auto",
    maxHeight: isNarrow ? 170 : undefined,
  },
  sectionLabel: {
    fontSize: typography.sectionTitle.size,
    fontWeight: typography.sectionTitle.weight,
    letterSpacing: typography.sectionTitle.tracking,
    textTransform: "uppercase",
    color: colors.textMuted,
    marginBottom: spacing.md,
  },
  docList: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.xs,
  },
  docRow: {
    display: "flex",
    alignItems: "center",
    gap: spacing.sm,
    width: "100%",
    padding: `${spacing.sm}px ${spacing.md}px`,
    border: `1px solid transparent`,
    borderRadius: radius.sm,
    background: "transparent",
    color: colors.text,
    textAlign: "left",
    cursor: "pointer",
  },
  docRowActive: {
    background: colors.surfaceHover,
    borderColor: colors.border,
  },
  ext: {
    minWidth: 30,
    borderRadius: radius.xs,
    border: `1px solid ${colors.border}`,
    color: colors.textMuted,
    fontSize: typography.meta.size,
    textAlign: "center",
    padding: `1px ${spacing.xs}px`,
  },
  docName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: typography.chatBody.size,
    fontWeight: 600,
  },
  documentPane: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    padding: isNarrow ? spacing.md : spacing.xl,
    gap: isNarrow ? spacing.md : spacing.lg,
  },
  header: {
    display: "flex",
    flexDirection: isNarrow ? "column" : "row",
    justifyContent: "space-between",
    alignItems: isNarrow ? "stretch" : "flex-start",
    gap: spacing.lg,
  },
  docTitle: {
    color: colors.text,
    fontSize: typography.docHeading.size,
    fontWeight: typography.docHeading.weight,
    lineHeight: typography.docHeading.lineHeight,
  },
  docPath: {
    marginTop: spacing.xs,
    color: colors.textMuted,
    fontSize: typography.meta.size,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: spacing.sm,
    flexWrap: "wrap",
    justifyContent: isNarrow ? "flex-start" : "flex-end",
  },
  segmented: {
    display: "flex",
    padding: spacing.xxs,
    borderRadius: radius.pill,
    background: colors.surfaceHover,
    border: `1px solid ${colors.border}`,
  },
  segmentButton: {
    border: "none",
    borderRadius: radius.pill,
    background: "transparent",
    color: colors.textMuted,
    fontSize: typography.meta.size,
    fontWeight: 700,
    padding: `${spacing.xs}px ${spacing.md}px`,
    cursor: "pointer",
  },
  segmentButtonActive: {
    background: colors.surface,
    color: colors.text,
    boxShadow: shadow.card,
  },
  primaryButton: {
    border: `1px solid ${colors.accent}`,
    borderRadius: radius.sm,
    background: colors.accent,
    color: colors.bg,
    fontSize: typography.meta.size,
    fontWeight: 800,
    padding: `${spacing.sm}px ${spacing.md}px`,
    cursor: "pointer",
  },
  body: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    background: colors.surface,
    boxShadow: shadow.card,
  },
  preview: {
    maxWidth: 760,
    margin: "0 auto",
    padding: isNarrow ? `${spacing.xl}px ${spacing.lg}px` : `${spacing.xxxl}px ${spacing.xxl}px`,
    color: colors.text,
    fontFamily: fontFamilies.doc,
    fontSize: typography.documentBody.size,
    lineHeight: typography.documentBody.lineHeight,
  },
  editor: {
    width: "100%",
    height: "100%",
    minHeight: 420,
    resize: "none",
    border: "none",
    outline: "none",
    background: colors.surface,
    color: colors.text,
    padding: spacing.xxl,
    fontFamily: fontFamilies.mono,
    fontSize: typography.documentBody.size,
    lineHeight: typography.documentBody.lineHeight,
  },
  empty: {
    color: colors.textMuted,
    fontSize: typography.chatBody.size,
    padding: spacing.xxl,
  },
});
