/**
 * HandleInputRoute — process route result and determine next action.
 *
 * Handles: chitchat, light_response, command, ambiguous, task
 * For "task", returns the task seed for further processing.
 */

import type { InputRoute, CouncilMessage } from "@agora/shared";

interface HandleInputRouteResult {
  action: "fast_reply" | "direct_reply" | "command" | "clarify" | "proceed_to_task";
  fastReply?: string;
  directReply?: string;
  command?: string;
  clarificationQuestion?: string;
  taskSeed?: string;
}

/**
 * Process an InputRoute and determine the next action.
 * Returns action type + payload for the orchestration layer to execute.
 */
export function handleInputRoute(
  route: InputRoute,
  _recentMessages: CouncilMessage[],
): HandleInputRouteResult {
  switch (route.kind) {
    case "chitchat":
      return {
        action: "fast_reply",
        fastReply: route.fastReply,
      };

    case "light_response":
      return {
        action: "direct_reply",
        // directReply will be generated by moderator in orchestration
      };

    case "command":
      return {
        action: "command",
        command: route.command,
      };

    case "ambiguous":
      return {
        action: "clarify",
        clarificationQuestion: route.clarificationQuestion,
      };

    case "task":
      return {
        action: "proceed_to_task",
        taskSeed: route.taskSeed,
      };
  }
}
