import type { ColorPalette } from "../theme/palettes.js";
import { spacing, radius, typography, motion, shadow, layout } from "../theme/tokens.js";

export const createComposerStyles = (colors: ColorPalette): Record<string, React.CSSProperties> => ({
  // ─── Container ─────────────────────────────────────────────────────
  container: {
    padding: `${spacing.sm}px ${spacing.md}px`,
    position: "relative",
  },

  // ─── Chips ─────────────────────────────────────────────────────────
  chipsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: spacing.xs,
    marginBottom: spacing.sm,
  },
  chip: {
    display: "flex",
    alignItems: "center",
    gap: spacing.xxs,
    padding: `${spacing.xxs}px ${spacing.sm}px`,
    borderRadius: radius.xs,
    background: `${colors.accent}11`,
    color: colors.text,
    fontSize: typography.meta.size,
    lineHeight: typography.meta.lineHeight,
    border: `1px solid ${colors.border}`,
  },
  chipRole: {
    borderColor: colors.accent,
    background: `${colors.accent}15`,
  },
  chipIcon: {
    color: colors.accent,
    fontWeight: 700,
    fontSize: typography.meta.size,
  },
  chipRemove: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: 10,
    padding: `0 ${spacing.xxs}px`,
    lineHeight: 1,
  },

  // ─── Input area ────────────────────────────────────────────────────
  inputArea: {
    display: "flex",
    alignItems: "flex-end",
    gap: spacing.sm,
  },
  textarea: {
    flex: 1,
    background: colors.bg,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    padding: `${spacing.sm}px ${spacing.md}px`,
    color: colors.text,
    fontSize: typography.chatBody.size,
    lineHeight: typography.chatBody.lineHeight,
    resize: "none",
    outline: "none",
    fontFamily: "inherit",
    minHeight: 36,
    maxHeight: 160,
    transition: `border-color ${motion.fast}`,
  },

  // ─── Send / Stop button ────────────────────────────────────────────
  sendBtn: {
    width: 36,
    height: 36,
    borderRadius: radius.md,
    background: colors.accent,
    border: "none",
    color: "#fff",
    cursor: "pointer",
    fontSize: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: `opacity ${motion.fast}`,
  },
  sendBtnDisabled: {
    opacity: 0.4,
    cursor: "default",
  },

  // ─── Bottom toolbar ────────────────────────────────────────────────
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: spacing.xxs,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTop: `1px solid ${colors.border}`,
  },
  toolbarBtn: {
    background: "none",
    border: `1px solid transparent`,
    borderRadius: radius.xs,
    padding: `${spacing.xxs}px ${spacing.sm}px`,
    color: colors.textMuted,
    fontSize: typography.meta.size,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: spacing.xxs,
    transition: `all ${motion.fast}`,
    whiteSpace: "nowrap",
  },
  toolbarBtnActive: {
    borderColor: colors.accent,
    color: colors.accent,
    background: `${colors.accent}08`,
  },
  toolbarSpacer: { flex: 1 },

  // ─── Popover (shared) ──────────────────────────────────────────────
  popover: {
    position: "absolute",
    bottom: "100%",
    left: spacing.md,
    marginBottom: spacing.sm,
    background: "var(--panel-solid)",
    border: "1px solid var(--line)",
    borderRadius: radius.lg,
    padding: spacing.md,
    boxShadow: "0 14px 44px rgba(0, 0, 0, .28)",
    minWidth: 240,
    maxWidth: 320,
    zIndex: 50,
  },
  popoverTitle: {
    fontSize: typography.sectionTitle.size,
    fontWeight: typography.sectionTitle.weight,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: typography.sectionTitle.tracking,
    marginBottom: spacing.sm,
  },
  popoverRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: `${spacing.xs}px 0`,
    fontSize: typography.meta.size,
    color: colors.text,
  },
  popoverValue: {
    color: colors.textMuted,
    fontSize: typography.meta.size,
  },
  popoverOption: {
    display: "block",
    width: "100%",
    textAlign: "left",
    background: "none",
    border: "none",
    borderRadius: radius.xs,
    padding: `${spacing.xs}px ${spacing.sm}px`,
    color: colors.text,
    fontSize: typography.meta.size,
    cursor: "pointer",
    transition: `background ${motion.fast}`,
  },
  popoverOptionSelected: {
    background: `${colors.accent}11`,
    color: colors.accent,
  },

  // ─── Add menu ──────────────────────────────────────────────────────
  addMenu: {
    position: "absolute",
    bottom: "100%",
    left: spacing.md,
    marginBottom: spacing.sm,
    background: "var(--panel-solid)",
    border: "1px solid var(--line)",
    borderRadius: radius.lg,
    padding: `${spacing.xs}px 0`,
    boxShadow: "0 14px 44px rgba(0, 0, 0, .28)",
    minWidth: 180,
    zIndex: 50,
  },
  addMenuItem: {
    display: "flex",
    alignItems: "center",
    gap: spacing.sm,
    width: "100%",
    textAlign: "left",
    background: "none",
    border: "none",
    borderRadius: 0,
    padding: `${spacing.sm}px ${spacing.md}px`,
    color: colors.text,
    fontSize: typography.meta.size,
    cursor: "pointer",
    transition: `background ${motion.fast}`,
  },
});
