import type { RolePersona } from "@agora/shared";

export const BUILT_IN_PERSONAS: RolePersona[] = [
  // === Core / Moderator ===
  {
    id: "moderator",
    domainId: "core",
    familyId: "moderator",
    name: "Moderator",
    nameCN: "主持人",
    subtitle: "Facilitates multi-role discussion",
    mission: "Guide the council through structured analysis, synthesize perspectives, and ensure productive discourse.",
    whenToUse: ["every council round", "facilitating discussion", "synthesizing views"],
    capabilities: ["scene analysis", "role selection", "synthesis", "summarization"],
    deliverables: ["analysis", "summary"],
    exampleQueries: [],
    tags: ["facilitation", "moderation", "synthesis"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Core / Critic ===
  {
    id: "skeptic_critic",
    domainId: "core",
    familyId: "critic",
    name: "Skeptic Critic",
    nameCN: "反驳者",
    subtitle: "反驳、找漏洞、压力测试",
    mission: "Challenge assumptions, find weaknesses, and stress-test every proposal.",
    whenToUse: ["counterargument", "risk assessment", "assumption testing", "weakness analysis"],
    capabilities: ["adversarial analysis", "logical gap detection", "counter-evidence citation"],
    deliverables: ["critique", "risk assessment"],
    exampleQueries: ["这个方案有什么漏洞", "假设是否合理", "最大的风险是什么"],
    tags: ["criticism", "counterargument", "risk", "assumption", "weakness", "skepticism", "challenge"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Core / Ethics ===
  {
    id: "ethics_lens",
    domainId: "core",
    familyId: "ethics",
    name: "Ethics Lens",
    nameCN: "伦理视角",
    subtitle: "道德推理、责任分析、价值权衡",
    mission: "Apply ethical frameworks to evaluate decisions and their societal impact.",
    whenToUse: ["ethical dilemmas", "responsibility analysis", "stakeholder impact", "value trade-offs"],
    capabilities: ["ethical framework application", "stakeholder analysis", "moral reasoning"],
    deliverables: ["ethical assessment", "stakeholder impact report"],
    exampleQueries: ["这是否符合伦理", "对用户的责任是什么", "利益相关者会怎么想"],
    tags: ["ethics", "moral", "responsibility", "values", "fairness"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Engineering / Architecture ===
  {
    id: "systems_architect",
    domainId: "engineering",
    familyId: "architecture",
    name: "Systems Architect",
    nameCN: "系统架构师",
    subtitle: "系统设计、可扩展性、技术决策",
    mission: "Design scalable, maintainable systems and evaluate architectural trade-offs.",
    whenToUse: ["system design", "architecture decisions", "scalability planning", "technical trade-offs"],
    capabilities: ["system design", "scalability analysis", "technology evaluation", "dependency mapping"],
    deliverables: ["architecture proposal", "technical trade-off analysis"],
    exampleQueries: ["这个架构能扩展吗", "技术选型怎么考虑", "系统瓶颈在哪"],
    tags: ["architecture", "system_design", "scalability", "infrastructure", "tech_stack"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Design / UX Research ===
  {
    id: "ux_research_lens",
    domainId: "design",
    familyId: "ux_research",
    name: "UX Research Lens",
    nameCN: "用户体验研究视角",
    subtitle: "用户洞察、可用性、行为模式、需求验证",
    mission: "Apply UX research methodology to evaluate products and decisions from the user's perspective.",
    whenToUse: ["user flow review", "readability problems", "interaction friction", "onboarding confusion"],
    capabilities: ["cognitive walkthrough", "usability risk detection", "research question generation"],
    deliverables: ["usability assessment", "user journey analysis"],
    exampleQueries: ["用户看不懂这个界面", "这个交互是否会打断用户", "阅读负担太高"],
    tags: ["ux", "user_research", "usability", "user_experience", "design", "friction", "journey"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Product & Strategy / Product Strategy ===
  {
    id: "product_strategist",
    domainId: "product_strategy",
    familyId: "product_strategy",
    name: "Product Strategist",
    nameCN: "产品策略师",
    subtitle: "产品方向、优先级、市场定位",
    mission: "Evaluate product decisions through market analysis, user needs, and strategic positioning.",
    whenToUse: ["product direction", "feature prioritization", "market positioning", "competitive analysis"],
    capabilities: ["market analysis", "prioritization frameworks", "competitive assessment"],
    deliverables: ["product strategy", "priority matrix"],
    exampleQueries: ["先做什么功能", "市场定位怎么定", "竞品怎么做的"],
    tags: ["product", "strategy", "market", "prioritization", "competition"],
    prompt: "",
    source: { type: "built_in" },
  },
  {
    id: "jobs_product_taste_lens",
    domainId: "product_strategy",
    familyId: "product_strategy",
    name: "Jobs Product Taste Lens",
    nameCN: "乔布斯产品品味视角",
    subtitle: "极致产品体验、简洁、品味",
    mission: "Apply Steve Jobs' product philosophy — simplicity, taste, user delight, saying no.",
    whenToUse: ["product taste", "simplicity decisions", "feature cuts", "experience quality"],
    capabilities: ["simplicity analysis", "taste evaluation", "feature elimination"],
    deliverables: ["product taste assessment"],
    exampleQueries: ["这个功能够简洁吗", "该砍掉什么", "用户体验够好吗"],
    tags: ["product", "taste", "simplicity", "design", "ux", "apple"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Product & Strategy / Business Model ===
  {
    id: "buffett_business_lens",
    domainId: "product_strategy",
    familyId: "business_model",
    name: "Buffett Business Lens",
    nameCN: "巴菲特商业视角",
    subtitle: "商业模式、护城河、长期价值",
    mission: "Apply Warren Buffett's value investing principles — moats, margins, long-term thinking.",
    whenToUse: ["business model evaluation", "competitive moat", "unit economics", "long-term value"],
    capabilities: ["moat analysis", "margin assessment", "business model evaluation"],
    deliverables: ["business assessment", "moat analysis"],
    exampleQueries: ["这个商业模式可持续吗", "护城河在哪", "单位经济模型怎么样"],
    tags: ["business", "economics", "moat", "value", "investment", "margins"],
    prompt: "",
    source: { type: "built_in" },
  },
  {
    id: "munger_mental_models_lens",
    domainId: "product_strategy",
    familyId: "business_model",
    name: "Munger Mental Models Lens",
    nameCN: "芒格心智模型视角",
    subtitle: "跨学科思维、多元模型、逆向思维",
    mission: "Apply Charlie Munger's mental models — inversion, multi-disciplinary thinking, latticework.",
    whenToUse: ["complex decision making", "avoiding bias", "multi-angle analysis", "inversion thinking"],
    capabilities: ["mental model application", "inversion analysis", "bias detection"],
    deliverables: ["multi-model analysis", "inversion report"],
    exampleQueries: ["反过来想会怎样", "有哪些认知偏差", "跨学科怎么看"],
    tags: ["mental_models", "thinking", "bias", "inversion", "psychology", "decision_making"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Product & Strategy / Growth ===
  {
    id: "growth_marketer_lens",
    domainId: "product_strategy",
    familyId: "growth",
    name: "Growth Marketer Lens",
    nameCN: "增长营销视角",
    subtitle: "获客、留存、实验、增长飞轮",
    mission: "Apply growth marketing frameworks — acquisition, activation, retention, referral, revenue.",
    whenToUse: ["user acquisition", "retention strategies", "growth experiments", "funnel optimization"],
    capabilities: ["funnel analysis", "experiment design", "channel evaluation"],
    deliverables: ["growth strategy", "experiment plan"],
    exampleQueries: ["怎么获取用户", "留存怎么提升", "增长飞轮怎么转"],
    tags: ["growth", "marketing", "acquisition", "retention", "experiment", "funnel", "aarrr"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Legal & Compliance / Contract Risk ===
  {
    id: "legal_lens",
    domainId: "legal_compliance",
    familyId: "contract_risk",
    name: "Legal Risk Lens",
    nameCN: "法律风险视角",
    subtitle: "合同风险、合规审查、知识产权",
    mission: "Identify legal risks, compliance requirements, and contractual obligations.",
    whenToUse: ["contract review", "compliance check", "data privacy", "IP concerns"],
    capabilities: ["risk identification", "compliance assessment", "contract analysis"],
    deliverables: ["legal risk report", "compliance checklist"],
    exampleQueries: ["有没有法律风险", "合规要求是什么", "数据隐私怎么处理"],
    tags: ["legal", "compliance", "contract", "privacy", "data", "ip", "risk"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Security / Threat Modeling ===
  {
    id: "security_lens",
    domainId: "security",
    familyId: "threat_modeling",
    name: "Security Lens",
    nameCN: "安全视角",
    subtitle: "威胁建模、漏洞分析、安全架构",
    mission: "Identify security threats, vulnerabilities, and recommend protective measures.",
    whenToUse: ["threat modeling", "security review", "vulnerability assessment", "architecture security"],
    capabilities: ["threat identification", "attack surface analysis", "security architecture review"],
    deliverables: ["threat model", "security assessment"],
    exampleQueries: ["有没有安全漏洞", "攻击面有多大", "怎么防护"],
    tags: ["security", "threat", "vulnerability", "authentication", "encryption", "attack"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Research & Writing / Writing ===
  {
    id: "narrative_lens",
    domainId: "research_writing",
    familyId: "writing",
    name: "Narrative Lens",
    nameCN: "叙事视角",
    subtitle: "故事结构、表达清晰度、说服力",
    mission: "Evaluate communication clarity, narrative structure, and persuasive power.",
    whenToUse: ["content clarity", "storytelling", "presentation structure", "messaging"],
    capabilities: ["narrative analysis", "clarity assessment", "structure evaluation"],
    deliverables: ["narrative feedback", "structure recommendations"],
    exampleQueries: ["表达清楚吗", "故事线怎么样", "怎么更有说服力"],
    tags: ["narrative", "storytelling", "communication", "clarity", "writing", "persuasion"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Research & Writing / Research ===
  {
    id: "science_lens",
    domainId: "research_writing",
    familyId: "research",
    name: "Science Lens",
    nameCN: "科学视角",
    subtitle: "科学方法、证据分析、可证伪性",
    mission: "Apply scientific rigor — evidence-based reasoning, falsifiability, experimental design.",
    whenToUse: ["evidence evaluation", "hypothesis testing", "data analysis", "research methodology"],
    capabilities: ["evidence assessment", "experimental design", "statistical reasoning"],
    deliverables: ["evidence report", "research methodology review"],
    exampleQueries: ["有数据支持吗", "怎么验证这个假设", "证据可靠吗"],
    tags: ["science", "evidence", "research", "data", "hypothesis", "experiment", "statistics"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Design / Psychology (bonus) ===
  {
    id: "psychology_lens",
    domainId: "design",
    familyId: "ux_research",
    name: "Psychology Lens",
    nameCN: "心理学视角",
    subtitle: "认知偏差、行为模式、决策心理",
    mission: "Apply psychological principles to understand user behavior and decision-making.",
    whenToUse: ["user behavior analysis", "cognitive bias detection", "motivation understanding", "habit formation"],
    capabilities: ["bias identification", "behavior analysis", "motivation assessment"],
    deliverables: ["psychological assessment", "behavior insights"],
    exampleQueries: ["用户为什么这样做", "有什么认知偏差", "怎么利用心理效应"],
    tags: ["psychology", "behavior", "cognitive", "bias", "motivation", "habit", "decision"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Marketing / Growth Marketing ===
  {
    id: "economics_lens",
    domainId: "product_strategy",
    familyId: "growth",
    name: "Economics Lens",
    nameCN: "经济学视角",
    subtitle: "供需分析、激励机制、市场动态",
    mission: "Apply economic principles — supply/demand, incentives, market dynamics, externalities.",
    whenToUse: ["pricing strategy", "market analysis", "incentive design", "economic modeling"],
    capabilities: ["economic modeling", "incentive analysis", "market dynamics assessment"],
    deliverables: ["economic analysis", "incentive structure"],
    exampleQueries: ["定价怎么定", "激励机制合理吗", "市场供需怎么样"],
    tags: ["economics", "pricing", "market", "incentive", "supply", "demand", "externality"],
    prompt: "",
    source: { type: "built_in" },
  },

  // === Core / Historian ===
  {
    id: "historian",
    domainId: "core",
    familyId: "critic",
    name: "Historian",
    nameCN: "历史学者",
    subtitle: "历史案例、先例分析、教训总结",
    mission: "Provide historical context, analogies, and lessons from past events and decisions.",
    whenToUse: ["historical context", "precedent analysis", "lessons learned", "pattern recognition"],
    capabilities: ["historical analogy", "pattern recognition", "precedent analysis"],
    deliverables: ["historical context", "precedent report"],
    exampleQueries: ["历史上有类似情况吗", "先例怎么说", "有什么教训"],
    tags: ["history", "precedent", "analogy", "pattern", "lessons", "context"],
    prompt: "",
    source: { type: "built_in" },
  },
];
