import type React from "react";
import type { ColorPalette } from "../theme/palettes.js";
import { layout, radius, spacing, typography, zIndex } from "../theme/tokens.js";

export const createAppShellStyles = (
  colors: ColorPalette,
): Record<string, React.CSSProperties> => ({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    overflow: "hidden",
  },
  mainLayout: {
    flex: 1,
    display: "flex",
    overflow: "hidden",
  },
  leftRail: {
    width: layout.miniGraph,
    flexShrink: 0,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    borderRight: `1px solid ${colors.border}`,
  },
  roomList: {
    display: "flex",
    flexDirection: "column",
    borderBottom: `1px solid ${colors.border}`,
    maxHeight: 200,
  },
  roomListHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: `${spacing.sm}px ${spacing.md}px`,
  },
  roomListTitle: {
    fontSize: typography.sectionTitle.size,
    fontWeight: typography.sectionTitle.weight,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: typography.sectionTitle.tracking,
  },
  newRoomBtn: {
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    width: 20,
    height: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: colors.accent,
    fontSize: 14,
    cursor: "pointer",
    lineHeight: 1,
  },
  roomListItems: {
    flex: 1,
    overflowY: "auto",
    padding: `0 ${spacing.sm}px ${spacing.sm}px`,
  },
  roomEmpty: {
    fontSize: typography.meta.size,
    color: colors.textMuted,
    padding: `${spacing.xs}px ${spacing.xs}px`,
  },
  roomItem: {
    display: "block",
    width: "100%",
    textAlign: "left",
    background: "none",
    border: "none",
    borderRadius: radius.xs,
    padding: `${spacing.xs + 1}px ${spacing.sm}px`,
    fontSize: typography.meta.size,
    color: colors.text,
    cursor: "pointer",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  roomItemActive: {
    background: `${colors.accent}11`,
    color: colors.accent,
  },
  chatRegion: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  chatContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    position: "relative" as const,
    overflow: "hidden",
  },
  chat: {
    flex: 1,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
  },
  chatHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: `${spacing.sm}px ${spacing.lg}px`,
    borderBottom: `1px solid ${colors.border}`,
    position: "relative" as const,
    zIndex: zIndex.header,
    background: colors.bg,
  },
  chatTitle: {
    fontSize: typography.sectionTitle.size,
    fontWeight: typography.sectionTitle.weight,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: typography.sectionTitle.tracking,
  },
  addRefBtn: {
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    padding: `${spacing.xxs}px ${spacing.sm}px`,
    color: colors.accent,
    fontSize: typography.meta.size,
    cursor: "pointer",
  },
  leftHeader: {
    display: "flex",
    flexDirection: "column" as const,
    position: "relative" as const,
  },
  expandBtn: {
    position: "absolute" as const,
    top: spacing.xs,
    right: spacing.xs,
    width: 22,
    height: 22,
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: colors.textMuted,
    fontSize: 12,
    cursor: "pointer",
    zIndex: zIndex.rail,
  },
});
