import { colors } from "../theme/tokens.js";

export const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
  },
  panel: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: 12,
    width: 440,
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 16px",
    borderBottom: `1px solid ${colors.border}`,
    fontSize: 14,
    fontWeight: 600,
    color: colors.text,
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: 16,
  },
  body: {
    padding: "12px 16px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  loading: {
    padding: 40,
    textAlign: "center",
    color: colors.textMuted,
    fontSize: 13,
  },
  label: {
    fontSize: 11,
    fontWeight: 600,
    color: colors.textMuted,
    marginTop: 6,
    textTransform: "uppercase" as const,
    letterSpacing: 0.5,
  },
  input: {
    background: colors.bg,
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 13,
    color: colors.text,
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  select: {
    background: colors.bg,
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 13,
    color: colors.text,
    outline: "none",
    width: "100%",
  },
  keyRow: {
    display: "flex",
    gap: 6,
    alignItems: "center",
  },
  clearBtn: {
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: "6px 10px",
    fontSize: 11,
    color: colors.textMuted,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  keyStatus: {
    fontSize: 11,
    marginTop: 2,
  },
  statusMissing: { color: "#e74c3c" },
  statusEnv: { color: colors.textMuted },
  statusSaved: { color: "#27ae60" },
  advancedToggle: {
    background: "none",
    border: "none",
    color: colors.accent,
    fontSize: 11,
    cursor: "pointer",
    textAlign: "left" as const,
    padding: "4px 0",
    marginTop: 4,
  },
  actions: {
    display: "flex",
    gap: 8,
    marginTop: 12,
  },
  saveBtn: {
    flex: 1,
    background: colors.accent,
    border: "none",
    borderRadius: 6,
    padding: "8px 0",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  testBtn: {
    flex: 1,
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: 6,
    padding: "8px 0",
    color: colors.text,
    fontSize: 13,
    cursor: "pointer",
  },
  testSuccess: {
    marginTop: 8,
    padding: "6px 10px",
    borderRadius: 6,
    background: "rgba(39,174,96,0.1)",
    border: "1px solid rgba(39,174,96,0.3)",
    color: "#27ae60",
    fontSize: 12,
  },
  testError: {
    marginTop: 8,
    padding: "6px 10px",
    borderRadius: 6,
    background: "rgba(231,76,60,0.1)",
    border: "1px solid rgba(231,76,60,0.3)",
    color: "#e74c3c",
    fontSize: 12,
  },
};
