import type { ColorPalette } from "../theme/palettes.js";
import { radius, spacing, typography, zIndex } from "../theme/tokens.js";

export const createStyles = (colors: ColorPalette): Record<string, React.CSSProperties> => ({
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: zIndex.modal,
  },
  panel: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.md,
    width: 440,
    maxHeight: "80vh",
    display: "flex",
    flexDirection: "column",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: `${spacing.md}px ${spacing.lg}px`,
    borderBottom: `1px solid ${colors.border}`,
    fontSize: typography.chatBody.size,
    fontWeight: 700,
    color: colors.text,
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: typography.chatBody.size,
  },
  tabBtn: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    color: colors.textMuted,
    fontSize: typography.meta.size,
    fontWeight: 700,
    cursor: "pointer",
    padding: "2px 0",
  },
  tabBtnActive: {
    color: colors.accent,
    borderBottomColor: colors.accent,
  },
  body: {
    padding: `${spacing.md}px ${spacing.lg}px`,
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: spacing.sm,
  },
  loading: {
    padding: spacing.xxxl,
    textAlign: "center",
    color: colors.textMuted,
    fontSize: typography.chatBody.size,
  },
  label: {
    fontSize: typography.meta.size,
    fontWeight: 700,
    color: colors.textMuted,
    marginTop: spacing.sm,
    textTransform: "uppercase" as const,
    letterSpacing: typography.sectionTitle.tracking,
  },
  input: {
    background: colors.bg,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    padding: `${spacing.sm - 2}px ${spacing.md - 2}px`,
    fontSize: typography.chatBody.size,
    color: colors.text,
    outline: "none",
    width: "100%",
    boxSizing: "border-box" as const,
  },
  select: {
    background: colors.bg,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    padding: `${spacing.sm - 2}px ${spacing.md - 2}px`,
    fontSize: typography.chatBody.size,
    color: colors.text,
    outline: "none",
    width: "100%",
  },
  keyRow: {
    display: "flex",
    gap: spacing.sm,
    alignItems: "center",
  },
  clearBtn: {
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    padding: `${spacing.sm - 2}px ${spacing.md - 2}px`,
    fontSize: typography.meta.size,
    color: colors.textMuted,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  keyStatus: {
    fontSize: typography.meta.size,
    marginTop: spacing.xxs,
  },
  statusMissing: { color: colors.danger },
  statusEnv: { color: colors.textMuted },
  statusSaved: { color: colors.success },
  advancedToggle: {
    background: "none",
    border: "none",
    color: colors.accent,
    fontSize: typography.meta.size,
    cursor: "pointer",
    textAlign: "left" as const,
    padding: `${spacing.xs}px 0`,
    marginTop: spacing.xs,
  },
  actions: {
    display: "flex",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  saveBtn: {
    flex: 1,
    background: colors.accent,
    border: "none",
    borderRadius: radius.xs,
    padding: `${spacing.sm}px 0`,
    color: "#fff",
    fontSize: typography.chatBody.size,
    fontWeight: 700,
    cursor: "pointer",
  },
  testBtn: {
    flex: 1,
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.xs,
    padding: `${spacing.sm}px 0`,
    color: colors.text,
    fontSize: typography.chatBody.size,
    cursor: "pointer",
  },
  testSuccess: {
    marginTop: spacing.sm,
    padding: `${spacing.sm - 2}px ${spacing.md - 2}px`,
    borderRadius: radius.xs,
    background: colors.successBg,
    border: `1px solid ${colors.successBorder}`,
    color: colors.success,
    fontSize: typography.meta.size,
  },
  testError: {
    marginTop: spacing.sm,
    padding: `${spacing.sm - 2}px ${spacing.md - 2}px`,
    borderRadius: radius.xs,
    background: colors.dangerBg,
    border: `1px solid ${colors.dangerBorder}`,
    color: colors.danger,
    fontSize: typography.meta.size,
  },
});
